# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 06:49
from __future__ import unicode_literals

import backpage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=128, verbose_name='广告信息')),
                ('fee', models.FloatField(default=0, verbose_name='广告费用')),
                ('time', models.DateField(auto_now=True, verbose_name='导入时间')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
                'db_table': 'advertisement',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startplace', models.CharField(max_length=32, null=True, verbose_name='起点')),
                ('endplace', models.CharField(max_length=32, null=True, verbose_name='终点')),
                ('center', models.CharField(max_length=256, null=True, verbose_name='中间节点')),
                ('createtime', models.DateField(null=True, verbose_name='创建时间')),
                ('remark', models.CharField(max_length=128, verbose_name='备注')),
            ],
            options={
                'verbose_name': '常用路线',
                'verbose_name_plural': '常用路线',
                'db_table': 'line',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateField(auto_now=True, verbose_name='发起时间')),
                ('endtime', models.DateField(null=True, verbose_name='结束时间')),
                ('startplace', models.CharField(max_length=32, null=True, verbose_name='起始地点')),
                ('endplace', models.CharField(max_length=32, null=True, verbose_name='终点')),
                ('fee', models.FloatField(default=0, verbose_name='费用')),
                ('score', models.IntegerField(default=0, verbose_name='租车人评分')),
                ('accepttime', models.DateField(null=True, verbose_name='接单时间')),
                ('finishtime', models.DateField(null=True, verbose_name='完成订单时间')),
                ('remark', models.CharField(max_length=256, verbose_name='租车人评价')),
                ('status', backpage.models.TinyIntField(choices=[(0, '保存订单'), (1, '预定订单'), (2, '发起订单'), (3, '订单被接受'), (4, '完成订单'), (5, '订单未完成结束')], default=0, verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now=True, verbose_name='服务时间')),
                ('remark', models.CharField(max_length=512, verbose_name='备注')),
                ('score', models.IntegerField(default=-1, verbose_name='评分')),
            ],
            options={
                'verbose_name': '服务信息',
                'verbose_name_plural': '服务信息',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=18, verbose_name='车牌号')),
                ('load', models.FloatField(default=0, verbose_name='载重')),
                ('width', models.FloatField(default=0, verbose_name='宽')),
                ('heigth', models.FloatField(default=0, verbose_name='高')),
                ('length', models.FloatField(default=0, verbose_name='长')),
                ('car_type', backpage.models.TinyIntField(choices=[(0, '待审核'), (1, '无类型'), (2, '普通货车'), (3, '厢式货车'), (4, '封闭货车'), (5, '罐式货车'), (6, '平板货车'), (7, '集装厢车'), (8, '自卸货车'), (9, '特殊结构货车')], db_column='type', default=0, verbose_name='车辆类型')),
                ('modelinfo', models.CharField(max_length=256, null=True, verbose_name='其他信息')),
                ('remark', models.CharField(max_length=32, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆',
                'db_table': 'truck',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', backpage.models.FixedCharField(max_length=11, verbose_name='账号')),
                ('name', models.CharField(default='无名', max_length=128, null=True, verbose_name='名字')),
                ('pre_login_time', models.DateField(auto_now=True, verbose_name='上次登录时间')),
                ('signup_time', models.DateField(auto_now=True, verbose_name='登录时间')),
                ('token', models.CharField(max_length=64, null=True)),
                ('user_type', backpage.models.TinyIntField(choices=[(0, '未分组'), (1, '租车人'), (2, '货车司机'), (3, '待审核用户')], db_column='type', default=0, verbose_name='用户类型')),
            ],
            options={
                'verbose_name': '基础用户',
                'verbose_name_plural': '基础用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Lessee',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backpage.User', verbose_name='用户id')),
                ('position', models.CharField(max_length=128, null=True, verbose_name='即时位置')),
                ('score', models.IntegerField(default=0, verbose_name='信誉积分')),
                ('realname', models.CharField(max_length=128, verbose_name='真实姓名')),
                ('ci', models.CharField(max_length=18, null=True, verbose_name='身份证号')),
            ],
            options={
                'verbose_name': '货车主',
                'verbose_name_plural': '货车主',
                'db_table': 'lessee',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backpage.User', verbose_name='用户id')),
                ('position', models.CharField(max_length=128, null=True, verbose_name='即时位置')),
                ('score', models.IntegerField(default=0, verbose_name='用户积分')),
            ],
            options={
                'verbose_name': '租车者',
                'verbose_name_plural': '租车者',
                'db_table': 'rental',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='customer',
            field=models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.CASCADE, to='backpage.User', verbose_name='客户id'),
        ),
        migrations.AddField(
            model_name='service',
            name='offer',
            field=models.ForeignKey(db_column='offer', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='服务员id'),
        ),
        migrations.AddField(
            model_name='truck',
            name='lessee',
            field=models.ForeignKey(db_column='lessee', on_delete=django.db.models.deletion.CASCADE, to='backpage.Lessee', verbose_name='货车主id'),
        ),
        migrations.AddField(
            model_name='orders',
            name='lessee',
            field=models.ForeignKey(db_column='lessee', null=True, on_delete=django.db.models.deletion.CASCADE, to='backpage.Lessee', verbose_name='货车主id'),
        ),
        migrations.AddField(
            model_name='orders',
            name='rental',
            field=models.ForeignKey(db_column='rental', on_delete=django.db.models.deletion.CASCADE, to='backpage.Rental', verbose_name='租车者id'),
        ),
        migrations.AddField(
            model_name='line',
            name='lessee',
            field=models.ForeignKey(db_column='lessee', null=True, on_delete=django.db.models.deletion.CASCADE, to='backpage.Lessee', verbose_name='货车主id'),
        ),
        migrations.AddField(
            model_name='line',
            name='rental',
            field=models.ForeignKey(db_column='rental', on_delete=django.db.models.deletion.CASCADE, to='backpage.Rental', verbose_name='租车者id'),
        ),
    ]
