# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='lessee',
            field=models.OneToOneField(blank=True, db_column='lessee', null=True, on_delete=django.db.models.deletion.CASCADE, to='backpage.Lessee', verbose_name='货车主id'),
        ),
    ]
