# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 02:10
from __future__ import unicode_literals

import backpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='trucktype',
            field=models.IntegerField(choices=[(0, '小型货车'), (1, '大型货车'), (2, '小型平板'), (3, '中型平板'), (4, '大型平板')], default=0, verbose_name='货车类型'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=backpage.models.TinyIntField(choices=[(0, '系统选车订单'), (1, '自主选车订单'), (2, '长期订单'), (3, '订单被接受'), (4, '完成订单'), (5, '订单未完成结束')], default=0, verbose_name='订单状态'),
        ),
    ]
